/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authForgottenPasswordRouteImport } from './routes/(auth)/forgotten-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authTwoFactorRouteImport } from './routes/(auth)/two-factor'
import { Route as authenticatedAcceptInvitationRouteImport } from './routes/(authenticated)/accept-invitation'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as authenticatedOnboardingRouteImport } from './routes/(authenticated)/onboarding'
import { Route as authenticatedOrganizationRouteImport } from './routes/(authenticated)/organization'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgottenPasswordRoute = authForgottenPasswordRouteImport.update({
  id: '/forgotten-password',
  path: '/forgotten-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authTwoFactorRoute = authTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => authRouteRoute,
} as any)
const authenticatedAcceptInvitationRoute =
  authenticatedAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedOnboardingRoute = authenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedOrganizationRoute =
  authenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgotten-password': typeof authForgottenPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-up': typeof authSignUpRoute
  '/two-factor': typeof authTwoFactorRoute
  '/accept-invitation': typeof authenticatedAcceptInvitationRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/onboarding': typeof authenticatedOnboardingRoute
  '/organization': typeof authenticatedOrganizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotten-password': typeof authForgottenPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-up': typeof authSignUpRoute
  '/two-factor': typeof authTwoFactorRoute
  '/accept-invitation': typeof authenticatedAcceptInvitationRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/onboarding': typeof authenticatedOnboardingRoute
  '/organization': typeof authenticatedOrganizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(auth)/forgotten-password': typeof authForgottenPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/two-factor': typeof authTwoFactorRoute
  '/(authenticated)/accept-invitation': typeof authenticatedAcceptInvitationRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(authenticated)/onboarding': typeof authenticatedOnboardingRoute
  '/(authenticated)/organization': typeof authenticatedOrganizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/two-factor'
    | '/accept-invitation'
    | '/dashboard'
    | '/onboarding'
    | '/organization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/two-factor'
    | '/accept-invitation'
    | '/dashboard'
    | '/onboarding'
    | '/organization'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authenticated)'
    | '/(auth)/forgotten-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/sign-up'
    | '/(auth)/two-factor'
    | '/(authenticated)/accept-invitation'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/onboarding'
    | '/(authenticated)/organization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgotten-password': {
      id: '/(auth)/forgotten-password'
      path: '/forgotten-password'
      fullPath: '/forgotten-password'
      preLoaderRoute: typeof authForgottenPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/two-factor': {
      id: '/(auth)/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof authTwoFactorRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authenticated)/accept-invitation': {
      id: '/(authenticated)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authenticatedAcceptInvitationRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/onboarding': {
      id: '/(authenticated)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authenticatedOnboardingRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/organization': {
      id: '/(authenticated)/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof authenticatedOrganizationRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgottenPasswordRoute: typeof authForgottenPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignUpRoute: typeof authSignUpRoute
  authTwoFactorRoute: typeof authTwoFactorRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgottenPasswordRoute: authForgottenPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignUpRoute: authSignUpRoute,
  authTwoFactorRoute: authTwoFactorRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authenticatedRouteRouteChildren {
  authenticatedAcceptInvitationRoute: typeof authenticatedAcceptInvitationRoute
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedOnboardingRoute: typeof authenticatedOnboardingRoute
  authenticatedOrganizationRoute: typeof authenticatedOrganizationRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAcceptInvitationRoute: authenticatedAcceptInvitationRoute,
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedOnboardingRoute: authenticatedOnboardingRoute,
  authenticatedOrganizationRoute: authenticatedOrganizationRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
