FROM oven/bun:1.3.14 AS base

WORKDIR /app

COPY package.json bun.lock tsconfig.base.json tsconfig.json biome.json ./
COPY apps ./apps
COPY packages ./packages

RUN bun install --frozen-lockfile

WORKDIR /app/apps/api
EXPOSE 3001
CMD ["bun", "run", "dev"]
